### ISSUE TITLE
White list friends

### ISSUE THREAD

**Issue by DeFFIx** [tompointexe/VRCF-IBot#1]
I suggest adding a whitelist of friends to whom an invite will be sent when an invite is requested.

**Comment by tompointexe** [comment]
Yes, I could do it, but this code is ment to add player as friends, and for the account using this script to be in join me in the instance you want to invite people in !

As of rate limits, i cant have this script manage the invites without it beeing slow af !! (aprox 120 invites per hour, without accepting any friend request ... ) so yeah ... for small, friend only, party's I'l sadly suggest not to use this script !!
